//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_TourismAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class КЛИЕНТЫ
    {
        public КЛИЕНТЫ()
        {
            this.ПОЕЗДКИ = new HashSet<ПОЕЗДКИ>();
        }
    
        public int КЛИЕНТ_ID { get; set; }
        public string ФИО { get; set; }
        public string Данные_паспорта { get; set; }
        public string Пароль { get; set; }
    
        public virtual ICollection<ПОЕЗДКИ> ПОЕЗДКИ { get; set; }
    }
}
