//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_TourismAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class МАРШРУТЫ
    {
        public МАРШРУТЫ()
        {
            this.ПОЕЗДКИ = new HashSet<ПОЕЗДКИ>();
        }
    
        public int МАРШРУТ_ID { get; set; }
        public string Страна_назначения { get; set; }
        public string Цель_поездки { get; set; }
        public Nullable<decimal> Стоимость_1_дня_пребывания { get; set; }
        public Nullable<decimal> Стоимость_транспортных_услуг { get; set; }
        public Nullable<decimal> Стоимость_оформления_визы { get; set; }
    
        public virtual ICollection<ПОЕЗДКИ> ПОЕЗДКИ { get; set; }
    }
}
