//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_TourismAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПОЕЗДКИ
    {
        public int ПОЕЗДКА_ID { get; set; }
        public Nullable<int> КЛИЕНТ_ID { get; set; }
        public Nullable<int> МАРШРУТ_ID { get; set; }
        public Nullable<System.DateTime> Дата_начала_поездки { get; set; }
        public Nullable<int> Количество_дней { get; set; }
    
        public virtual КЛИЕНТЫ КЛИЕНТЫ { get; set; }
        public virtual МАРШРУТЫ МАРШРУТЫ { get; set; }
    }
}
